FROM mosthege/pythonnet:python3.11.1-mono6.12-pythonnet3.0.1

WORKDIR /dll

COPY . /dll

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8010", "--reload"]