# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.tdms_service_pb2 as tdms__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tdms_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TdmsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadTdms = channel.unary_stream(
                '/tdms_service.TdmsService/ReadTdms',
                request_serializer=tdms__service__pb2.TdmsReadRequest.SerializeToString,
                response_deserializer=tdms__service__pb2.TdmsReadResponse.FromString,
                _registered_method=True)
        self.SendTdms = channel.unary_unary(
                '/tdms_service.TdmsService/SendTdms',
                request_serializer=tdms__service__pb2.TdmsSendRequest.SerializeToString,
                response_deserializer=tdms__service__pb2.TdmsSendResponse.FromString,
                _registered_method=True)
        self.ReceivedData = channel.unary_unary(
                '/tdms_service.TdmsService/ReceivedData',
                request_serializer=tdms__service__pb2.DataReceivedRequest.SerializeToString,
                response_deserializer=tdms__service__pb2.DataReceivedResponse.FromString,
                _registered_method=True)


class TdmsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadTdms(self, request, context):
        """🔹 TDMS 데이터 읽기
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTdms(self, request, context):
        """🔹 C#이 받은 데이터를 AI 서버로 전송
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceivedData(self, request, context):
        """🔹 AI Server에서 Inference 결과 가져오기
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TdmsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadTdms': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadTdms,
                    request_deserializer=tdms__service__pb2.TdmsReadRequest.FromString,
                    response_serializer=tdms__service__pb2.TdmsReadResponse.SerializeToString,
            ),
            'SendTdms': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTdms,
                    request_deserializer=tdms__service__pb2.TdmsSendRequest.FromString,
                    response_serializer=tdms__service__pb2.TdmsSendResponse.SerializeToString,
            ),
            'ReceivedData': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceivedData,
                    request_deserializer=tdms__service__pb2.DataReceivedRequest.FromString,
                    response_serializer=tdms__service__pb2.DataReceivedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tdms_service.TdmsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tdms_service.TdmsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TdmsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadTdms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tdms_service.TdmsService/ReadTdms',
            tdms__service__pb2.TdmsReadRequest.SerializeToString,
            tdms__service__pb2.TdmsReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTdms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tdms_service.TdmsService/SendTdms',
            tdms__service__pb2.TdmsSendRequest.SerializeToString,
            tdms__service__pb2.TdmsSendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceivedData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tdms_service.TdmsService/ReceivedData',
            tdms__service__pb2.DataReceivedRequest.SerializeToString,
            tdms__service__pb2.DataReceivedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
