# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tdms_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tdms_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12tdms_service.proto\x12\x0ctdms_service\"$\n\x0fTdmsReadRequest\x12\x11\n\ttdms_data\x18\x01 \x01(\t\"%\n\x10TdmsReadResponse\x12\x11\n\ttdms_data\x18\x01 \x01(\t\"3\n\x0fTdmsSendRequest\x12\x11\n\ttdms_data\x18\x01 \x01(\t\x12\r\n\x05timer\x18\x02 \x01(\x02\"\x12\n\x10TdmsSendResponse\"\x15\n\x13\x44\x61taReceivedRequest\"-\n\x14\x44\x61taReceivedResponse\x12\x15\n\rreceived_data\x18\x01 \x01(\t2\xfc\x01\n\x0bTdmsService\x12K\n\x08ReadTdms\x12\x1d.tdms_service.TdmsReadRequest\x1a\x1e.tdms_service.TdmsReadResponse0\x01\x12I\n\x08SendTdms\x12\x1d.tdms_service.TdmsSendRequest\x1a\x1e.tdms_service.TdmsSendResponse\x12U\n\x0cReceivedData\x12!.tdms_service.DataReceivedRequest\x1a\".tdms_service.DataReceivedResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tdms_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TDMSREADREQUEST']._serialized_start=36
  _globals['_TDMSREADREQUEST']._serialized_end=72
  _globals['_TDMSREADRESPONSE']._serialized_start=74
  _globals['_TDMSREADRESPONSE']._serialized_end=111
  _globals['_TDMSSENDREQUEST']._serialized_start=113
  _globals['_TDMSSENDREQUEST']._serialized_end=164
  _globals['_TDMSSENDRESPONSE']._serialized_start=166
  _globals['_TDMSSENDRESPONSE']._serialized_end=184
  _globals['_DATARECEIVEDREQUEST']._serialized_start=186
  _globals['_DATARECEIVEDREQUEST']._serialized_end=207
  _globals['_DATARECEIVEDRESPONSE']._serialized_start=209
  _globals['_DATARECEIVEDRESPONSE']._serialized_end=254
  _globals['_TDMSSERVICE']._serialized_start=257
  _globals['_TDMSSERVICE']._serialized_end=509
# @@protoc_insertion_point(module_scope)
